newtest

diff --git a/.github/workflows/contract-monitor.yml b/.github/workflows/contract-monitor.yml
--- a/.github/workflows/contract-monitor.yml
+++ b/.github/workflows/contract-monitor.yml
@@ -1,4 +1,3 @@
-
 name: Monitor Stellar Contract
 
 permissions:
@@ -6,12 +5,11 @@ permissions:
 
 on:
   push:
-    branches: [ test ]
+    branches: [ main ]
   pull_request:
 
-  workflow_dispatch:
-#  schedule:
-#    - cron: "0 6 * * *"
+schedule:
+  - cron: '0 8 * * 1'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
@@ -20,28 +18,25 @@ concurrency:
 env:
   RUSTFLAGS: -C debuginfo=0 # Do not produce debug symbols to keep memory usage down
   RUST_BACKTRACE: 1
+  CONTRACT_ID = CATRNPHYKNXAPNLHEYH55REB6YSAJLGCPA4YM6L3WUKSZOPI77M2UMKI
 
 jobs:
   monitor-contract:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-
-      - name: Install system dependencies
-        run:  sudo apt-get update && sudo apt-get install -y libudev-dev libdbus-1-dev libusb-1.0-0-dev pkg-config
       - uses: actions-rust-lang/setup-rust-toolchain@v1
 
       - uses: stellar/actions/rust-cache@main
 
       - name: Install Stellar CLI
-        run: cargo install stellar-cli --version 22.5.0
+        run: cargo install stellar-cli
 
       - name: Fetch contract and compute hash
         shell: bash
         run: |
           which stellar
-          stellar network add --rpc-url https://soroban-rpc.mainnet.stellar.gateway.fm --network-passphrase "Public Global Stellar Network ; September 2015" mainnet
-          stellar contract fetch --id CATRNPHYKNXAPNLHEYH55REB6YSAJLGCPA4YM6L3WUKSZOPI77M2UMKI --network mainnet | openssl sha512 > current_hash.txt
+          stellar network add --rpc-url https://mainnet.sorobanrpc.com --network-passphrase "Public Global Stellar Network ; September 2015" mainnet
+          stellar contract fetch --id ${{ env.CONTRACT_ID }} --network mainnet | openssl sha512 > current_hash.txt
           echo "Computed hash: $(cat current_hash.txt)"
           
 
@@ -51,11 +46,11 @@ jobs:
           current_hash=$(cat current_hash.txt)
           
           if [ "$stored_hash" != "$current_hash" ]; then
-            echo "Error: Contract hash has changed!"
-            echo "Stored hash: $stored_hash"
-            echo "Current hash: $current_hash"
-            echo "Please update contract/domain_[...].wasm file after verifying the contract change."
-            rm current_hash.txt
+            echo "Error: Contract hash has changed!" >> "$GITHUB_STEP_SUMMARY"
+            echo "Stored hash: $stored_hash" >> "$GITHUB_STEP_SUMMARY"
+            echo "Current hash: $current_hash" >> "$GITHUB_STEP_SUMMARY"
+            echo "Please update contract/domain_[...].wasm file after verifying the contract change." >> "$GITHUB_STEP_SUMMARY"
+            exit 1
           else
             echo "Contract hash matches stored hash at $(date -u)."
           fi
